version: '3.8'

services:
  bot:
    build: .
    container_name: game_results_bot
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - BOT_TOKEN=${8335049265:AAGjWzldB1DV6nsdFwMekC_YZsEdtkrlzWc}
      - DATABASE_URL=postgresql://game_results_db_rh8i_user:WcpLWFAKnD7Ezcf9QAnQmYHq6FFXRb2p@dpg-d66de3ggjchc73d6jfjg-a/game_results_db_rh8i
      - REDIS_URL=redis://red-d66dgfi48b3s73a4kdo0:6379
      - ADMIN_IDS=${638593776}
      - STEAM_API_KEY=${7DA945B46467DE86A1E0534DCA5F4790}
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    ports:
      - "5000:5000"
    command: python bot/main.py

  postgres:
    image: postgres:15-alpine
    container_name: game_bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: game_bot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
