services:
  - type: web
    name: game-results-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: BOT_TOKEN
        value: 8335049265:AAGjWzldB1DV6nsdFwMekC_YZsEdtkrlzWc
      - key: DATABASE_URL
        value: postgresql://game_results_db_rh8i_user:WcpLWFAKnD7Ezcf9QAnQmYHq6FFXRb2p@dpg-d66de3ggjchc73d6jfjg-a/game_results_db_rh8i
      - key: REDIS_URL
        value: redis://red-d66dgfi48b3s73a4kdo0:6379
      - key: WEBHOOK_HOST
        value: https://game-results-bot.onrender.com
      - key: ADMIN_IDS
        value: "638593776"
      - key: STEAM_API_KEY
        value: 7DA945B46467DE86A1E0534DCA5F4790
      - key: WOT_APPLICATION_ID
        sync: false
      - key: RIOT_API_KEY
        sync: false
      - key: PUBG_API_KEY
        sync: false
      - key: ZERO_CRYPTO_PAY_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
